### ISSUE TITLE
RE: Hello!

### ISSUE THREAD

**Issue by silver2row** [MomsFriendlyRobotCompany/pysabertooth#1]
Hello There,

My name is Seth. I goof around w/ items and learn things like most people interested in electronics and target boards. I am currently using the BBBW (BeagleBone Black Wireless) for software and hardware examples while online. 

Anyway...

Long story, short: Are you planning on updating this repository at any point? If it does not need additional ideas, okay. I am going to use it. I found it a while back and was hesitant at first but now I am feeling more comfortable w/ the BBBW and Python.

Seth

P.S. I installed, via `pip`, the library you made. I cannot wait to try it out. I have a SaberTooth 2 x 12 right now. If you get bored, please shoot a reply. If not, I will close this section of the "issue." Thank you for making this possible.

**Comment by walchko** [comment]
does it need updating? It works for us on this [R2-D2 project](https://github.com/DFEC-R2D2/r2d2) and so far we haven't needed anything more. If you find something wrong, feel free to submit a pull request.

**Comment by silver2row** [comment]
Hello,

No sir, I do not think the software needs updating. I thought since it was a year since things were updated, maybe updates were necessary. But if not, I do not want to get in the way.

I will look at the project. Thank you for replying.

Seth

**Comment by silver2row** [comment]
@walchko ,

Hello again...the project is super nice. Way to go! That looks like a ton of work and expertise went into that project.

Seth

P.S. I have been messing w/ the BeagleBone Black Wireless and the MotorCape for now. I cannot wait to test out this software. Thank you for producing it.

**Comment by silver2row** [comment]
Hello Again Sir,

I tested the software w/ a SaberTooth 2 x 12. W/ perfection, the example worked out. It worked so well, I was surprised about how easy it was to get up and running.

Seth

P.S. Nice!
