### ISSUE TITLE
Quick Question over (b'\xaa')??

### ISSUE THREAD

**Issue by ghost** [MomsFriendlyRobotCompany/pysabertooth#4]
hello Mr Walchko,
I was looking through you library, to gain a better understanding of how it works and noted the (b\xaa) writes, after opening a port, and setting up the baud rate. I'm curious as to what this is for? I've gone through the sabertooth manual, but may have missed any reference to it. Thank you so much.

**Comment by walchko** [comment]
sorry, I have not used this in a number of years ... I don't remember why I put that in the code. Looking through the manual, I agree with you, it isn't needed.

**Comment by ghost** [comment]
Hello Kevin,
Thank you so much for the speedy reply; it's highly appreciated.
I did some tests with those lines commented out, and everything on the
S60's seems to play nice.
Thanks again.
--Mike
