### ISSUE TITLE
Ideas for Building Locally without `python3 -m pip install`?

### ISSUE THREAD

**Issue by silver2row** [MomsFriendlyRobotCompany/pysabertooth#6]
Hello,

I wanted to change up your library and make it available for various file locations locally. 

For instance, I have some UART functionality outside of /dev/ttyUSB(N) and wanted to test with `/dev/bone/uart`.

I know this is asking a lot but I would like to use the lib. again.

Seth

P.S. Is there a way to support this lib. locally without using `python3 -m pip install` to install the lib. locally, i.e. setup.py or another form?

**Comment by walchko** [comment]
Hello! Sorry for the delay, I have been busy.

So, it uses the python serial library, so you should be able to pass any serial port path and it should work.

it uses `poetry`, so you can do `poetry install` and install it locally to work on it.

**Comment by silver2row** [comment]
Thank you sir...I appreciate you returning service. I tried with `hatch` as the build framework. Blah...anyway. I used poetry and it worked. Thank you again for keeping this lib. open and not deprecated. serial. Got it.

**Comment by walchko** [comment]
this is also MIT licensed, so if you would rather use `hatch` (not familiar with that) or make changes to it and republish it, feel free to fork! Good luck! :)
